"""empty message

Revision ID: 05eb69de718c
Revises: 
Create Date: 2022-04-27 21:03:56.515963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05eb69de718c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('no', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('no')
    )
    op.create_table('car',
    sa.Column('no', sa.Integer(), nullable=False),
    sa.Column('person_no', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(length=30), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['person_no'], ['person.no'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('no')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('car')
    op.drop_table('person')
    # ### end Alembic commands ###
